#!/usr/bin/env python3
"""
Script to add missing states and districts to database
"""

from database import engine, Base
from sqlalchemy.orm import sessionmaker
from models.base_location import State, District, City

# Create session
SessionLocal = sessionmaker(bind=engine)
db = SessionLocal()

def add_states_and_districts():
    """Add missing states and districts to database"""
    print("🗄️ Adding States and Districts")
    print("=" * 50)
    
    # Indian States with Districts and Cities
    states_to_add = [
        {"name": "Andhra Pradesh", "districts": [
            {"name": "Anantapur", "cities": ["Anantapur", "Guntakal", "Hindupur"]},
            {"name": "Chittoor", "cities": ["Chittoor", "Tirupati", "Madanapalle"]},
            {"name": "East Godavari", "cities": ["Kakinada", "Rajahmundry", "Amalapuram"]},
            {"name": "Guntur", "cities": ["Guntur", "Tenali", "Vijayawada"]},
            {"name": "Krishna", "cities": ["Vijayawada", "Machilipatnam", "Gudivada"]},
            {"name": "Kurnool", "cities": ["Kurnool", "Nandyal", "Adoni"]},
            {"name": "Nellore", "cities": ["Nellore", "Kavali", "Gudur"]},
            {"name": "Prakasam", "cities": ["Ongole", "Markapur", "Chirala"]},
            {"name": "Srikakulam", "cities": ["Srikakulam", "Amadalavalasa", "Palasa"]},
            {"name": "Visakhapatnam", "cities": ["Visakhapatnam", "Vizianagaram", "Anakapalle"]},
            {"name": "Vizianagaram", "cities": ["Vizianagaram", "Bobbili", "Salur"]},
            {"name": "West Godavari", "cities": ["Eluru", "Bhimavaram", "Tadepalligudem"]},
            {"name": "YSR Kadapa", "cities": ["Kadapa", "Proddatur", "Rayachoti"]}
        ]},
        {"name": "Arunachal Pradesh", "districts": [
            {"name": "Tawang", "cities": ["Tawang"]},
            {"name": "West Kameng", "cities": ["Bomdila", "Dirang"]},
            {"name": "East Kameng", "cities": ["Seppa"]},
            {"name": "Papum Pare", "cities": ["Itanagar", "Naharlagun"]},
            {"name": "Lower Subansiri", "cities": ["Ziro"]},
            {"name": "Upper Subansiri", "cities": ["Daporijo"]},
            {"name": "West Siang", "cities": ["Along"]},
            {"name": "East Siang", "cities": ["Pasighat"]},
            {"name": "Upper Siang", "cities": ["Yingkiong"]},
            {"name": "Lower Siang", "cities": ["Likabali"]},
            {"name": "Lohit", "cities": ["Tezu"]},
            {"name": "Namsai", "cities": ["Namsai"]},
            {"name": "Changlang", "cities": ["Changlang", "Miao"]},
            {"name": "Tirap", "cities": ["Khonsa"]},
            {"name": "Longding", "cities": ["Longding"]},
            {"name": "Kurung Kumey", "cities": ["Koloriang"]},
            {"name": "Kra Daadi", "cities": ["Palo"]},
            {"name": "Pakke-Kessang", "cities": ["Seijosa"]},
            {"name": "Kamle", "cities": ["Raga"]},
            {"name": "Shi Yomi", "cities": ["Tato"]},
            {"name": "Lepa Rada", "cities": ["Basar"]}
        ]},
        {"name": "Assam", "districts": [
            {"name": "Barpeta", "cities": ["Barpeta", "Sorbhog"]},
            {"name": "Bongaigaon", "cities": ["Bongaigaon", "Abhayapuri"]},
            {"name": "Cachar", "cities": ["Silchar", "Lakhipur"]},
            {"name": "Darrang", "cities": ["Mangaldoai", "Kharupetia"]},
            {"name": "Dibrugarh", "cities": ["Dibrugarh", "Duliajan"]},
            {"name": "Dhubri", "cities": ["Dhubri", "Bilasipara"]},
            {"name": "Dhemaji", "cities": ["Dhemaji", "Silapathar"]},
            {"name": "Dima Hasao", "cities": ["Haflong"]},
            {"name": "Goalpara", "cities": ["Goalpara", "Lakhipur"]},
            {"name": "Golaghat", "cities": ["Golaghat", "Sarupathar"]},
            {"name": "Hailakandi", "cities": ["Hailakandi"]},
            {"name": "Jorhat", "cities": ["Jorhat", "Mariani"]},
            {"name": "Kamrup Metropolitan", "cities": ["Guwahati", "Dispur"]},
            {"name": "Kamrup", "cities": ["Amingaon", "Rani"]},
            {"name": "Karbi Anglong", "cities": ["Diphu", "Hamren"]},
            {"name": "Karimganj", "cities": ["Karimganj", "Badarpur"]},
            {"name": "Kokrajhar", "cities": ["Kokrajhar", "Gossaigaon"]},
            {"name": "Lakhimpur", "cities": ["North Lakhimpur", "Boginadi"]},
            {"name": "Majuli", "cities": ["Majuli"]},
            {"name": "Morigaon", "cities": ["Morigaon"]},
            {"name": "Nagaon", "cities": ["Nagaon", "Hojai"]},
            {"name": "Nalbari", "cities": ["Nalbari"]},
            {"name": "Sivasagar", "cities": ["Sivasagar", "Nazira"]},
            {"name": "Sonitpur", "cities": ["Tezpur", "Biswanath Chariali"]},
            {"name": "South Salmara-Mankachar", "cities": ["Dhubri"]},
            {"name": "Tinsukia", "cities": ["Tinsukia", "Digboi", "Doom Dooma"]},
            {"name": "Udalguri", "cities": ["Udalguri", "Kalaigaon"]},
            {"name": "West Karbi Anglong", "cities": ["Baithalangso"]},
            {"name": "Baksa", "cities": ["Mushalpur", "Pathsala"]},
            {"name": "Barpeta", "cities": ["Barpeta", "Sorbhog"]},
            {"name": "Biswanath", "cities": ["Biswanath Chariali"]},
            {"name": "Bongaigaon", "cities": ["Bongaigaon"]},
            {"name": "Charaideo", "cities": ["Sonari"]},
            {"name": "Chirang", "cities": ["Kajalgaon"]},
            {"name": "Darrang", "cities": ["Mangaldoai"]},
            {"name": "Dhemaji", "cities": ["Dhemaji"]},
            {"name": "Dhubri", "cities": ["Dhubri"]},
            {"name": "Dibrugarh", "cities": ["Dibrugarh"]},
            {"name": "Goalpara", "cities": ["Goalpara"]},
            {"name": "Golaghat", "cities": ["Golaghat"]},
            {"name": "Hailakandi", "cities": ["Hailakandi"]},
            {"name": "Hojai", "cities": ["Hojai"]},
            {"name": "Jorhat", "cities": ["Jorhat"]},
            {"name": "Kamrup Metropolitan", "cities": ["Guwahati"]},
            {"name": "Kamrup", "cities": ["Gauhati"]},
            {"name": "Karbi Anglong", "cities": ["Diphu"]},
            {"name": "Karimganj", "cities": ["Karimganj"]},
            {"name": "Kokrajhar", "cities": ["Kokrajhar"]},
            {"name": "Lakhimpur", "cities": ["North Lakhimpur"]},
            {"name": "Majuli", "cities": ["Majuli"]},
            {"name": "Morigaon", "cities": ["Morigaon"]},
            {"name": "Nagaon", "cities": ["Nagaon"]},
            {"name": "Nalbari", "cities": ["Nalbari"]},
            {"name": "Sivasagar", "cities": ["Sivasagar"]},
            {"name": "Sonitpur", "cities": ["Tezpur"]},
            {"name": "South Salmara-Mankachar", "cities": ["Dhubri"]},
            {"name": "Tinsukia", "cities": ["Tinsukia"]},
            {"name": "Udalguri", "cities": ["Udalguri"]},
            {"name": "West Karbi Anglong", "cities": ["Hamren"]}
        ]},
        {"name": "Bihar", "districts": [
            {"name": "Araria", "cities": ["Araria", "Forbesganj"]},
            {"name": "Arwal", "cities": ["Arwal"]},
            {"name": "Aurangabad", "cities": ["Aurangabad", "Dehri"]},
            {"name": "Banka", "cities": ["Banka", "Bhagalpur"]},
            {"name": "Begusarai", "cities": ["Begusarai", "Barauni"]},
            {"name": "Bhagalpur", "cities": ["Bhagalpur", "Sultanganj"]},
            {"name": "Bhojpur", "cities": ["Arrah", "Jagdishpur"]},
            {"name": "Buxar", "cities": ["Buxar", "Dumraon"]},
            {"name": "Darbhanga", "cities": ["Darbhanga", "Laukaha"]},
            {"name": "East Champaran", "cities": ["Motihari", "Raxaul"]},
            {"name": "Gaya", "cities": ["Gaya", "Bodh Gaya"]},
            {"name": "Gopalganj", "cities": ["Gopalganj", "Mirganj"]},
            {"name": "Jamui", "cities": ["Jamui", "Jhajha"]},
            {"name": "Jehanabad", "cities": ["Jehanabad"]},
            {"name": "Kaimur", "cities": ["Bhabua", "Mohania"]},
            {"name": "Katihar", "cities": ["Katihar", "Manihari"]},
            {"name": "Khagaria", "cities": ["Khagaria", "Gogri"]},
            {"name": "Kishanganj", "cities": ["Kishanganj", "Bahadurganj"]},
            {"name": "Lakhisarai", "cities": ["Lakhisarai"]},
            {"name": "Madhepura", "cities": ["Madhepura", "Murliganj"]},
            {"name": "Madhubani", "cities": ["Madhubani", "Jhanjharpur"]},
            {"name": "Munger", "cities": ["Munger", "Jamalpur"]},
            {"name": "Muzaffarpur", "cities": ["Muzaffarpur", "Motipur"]},
            {"name": "Nalanda", "cities": ["Bihar Sharif", "Rajgir"]},
            {"name": "Nawada", "cities": ["Nawada", "Hisua"]},
            {"name": "Patna", "cities": ["Patna", "Patna City"]},
            {"name": "Purnia", "cities": ["Purnia", "Kasba"]},
            {"name": "Rohtas", "cities": ["Sasaram", "Dehri"]},
            {"name": "Saharsa", "cities": ["Saharsa", "Simri Bakhtiarpur"]},
            {"name": "Samastipur", "cities": ["Samastipur", "Dalsinghsarai"]},
            {"name": "Saran", "cities": ["Chhapra", "Marhaura"]},
            {"name": "Sheikhpura", "cities": ["Sheikhpura"]},
            {"name": "Sheohar", "cities": ["Sheohar"]},
            {"name": "Sitamarhi", "cities": ["Sitamarhi", "Janakpur"]},
            {"name": "Siwan", "cities": ["Siwan", "Maharajganj"]},
            {"name": "Supaul", "cities": ["Supaul", "Nirmali"]},
            {"name": "Vaishali", "cities": ["Hajipur", "Lalganj"]},
            {"name": "West Champaran", "cities": ["Bettiah", "Bagaha"]}
        ]},
        {"name": "Chhattisgarh", "districts": [
            {"name": "Balod", "cities": ["Balod", "Gurur"]},
            {"name": "Baloda Bazar", "cities": ["Baloda Bazar", "Bhatapara"]},
            {"name": "Balrampur", "cities": ["Balrampur", "Kusmi"]},
            {"name": "Bastar", "cities": ["Jagdalpur"]},
            {"name": "Bemetara", "cities": ["Bemetara"]},
            {"name": "Bijapur", "cities": ["Bijapur"]},
            {"name": "Bilaspur", "cities": ["Bilaspur", "Ratanpur"]},
            {"name": "Dantewada", "cities": ["Dantewada"]},
            {"name": "Dhamtari", "cities": ["Dhamtari", "Kurud"]},
            {"name": "Durg", "cities": ["Durg", "Bhilai", "Rajnandgaon"]},
            {"name": "Gariaband", "cities": ["Gariaband"]},
            {"name": "Janjgir-Champa", "cities": ["Janjgir", "Champa"]},
            {"name": "Jashpur", "cities": ["Jashpur", "Kunkuri"]},
            {"name": "Kabirdham", "cities": ["Kawardha"]},
            {"name": "Kanker", "cities": ["Kanker"]},
            {"name": "Kondagaon", "cities": ["Kondagaon"]},
            {"name": "Korba", "cities": ["Korba", "Katghora"]},
            {"name": "Koriya", "cities": ["Baikunthpur"]},
            {"name": "Mahasamund", "cities": ["Mahasamund", "Basna"]},
            {"name": "Mungeli", "cities": ["Mungeli"]},
            {"name": "Narayanpur", "cities": ["Narayanpur"]},
            {"name": "Raigarh", "cities": ["Raigarh", "Kharsia"]},
            {"name": "Raipur", "cities": ["Raipur", "Birgaon"]},
            {"name": "Rajnandgaon", "cities": ["Rajnandgaon", "Dongargarh"]},
            {"name": "Sukma", "cities": ["Sukma"]},
            {"name": "Surajpur", "cities": ["Surajpur"]},
            {"name": "Surguja", "cities": ["Ambikapur"]},
            {"name": "Sukma", "cities": ["Sukma"]},
            {"name": "Balrampur", "cities": ["Balrampur"]}
        ]},
        {"name": "Goa", "districts": [
            {"name": "North Goa", "cities": ["Panaji", "Mapusa", "Margao"]},
            {"name": "South Goa", "cities": ["Margao", "Vasco da Gama", "Ponda"]}
        ]},
        {"name": "Gujarat", "districts": [
            {"name": "Ahmedabad", "cities": ["Ahmedabad", "Gandhinagar"]},
            {"name": "Amreli", "cities": ["Amreli", "Rajula"]},
            {"name": "Anand", "cities": ["Anand", "Vallabh Vidyanagar"]},
            {"name": "Aravalli", "cities": ["Modasa"]},
            {"name": "Banaskantha", "cities": ["Palanpur", "Deesa"]},
            {"name": "Bharuch", "cities": ["Bharuch", "Ankleshwar"]},
            {"name": "Bhavnagar", "cities": ["Bhavnagar", "Alang"]},
            {"name": "Botad", "cities": ["Botad"]},
            {"name": "Chhota Udepur", "cities": ["Chhota Udepur"]},
            {"name": "Dahod", "cities": ["Dahod"]},
            {"name": "Dang", "cities": ["Ahwa"]},
            {"name": "Devbhoomi Dwarka", "cities": ["Dwarka"]},
            {"name": "Gir Somnath", "cities": ["Veraval", "Somnath"]},
            {"name": "Jamnagar", "cities": ["Jamnagar", "Khambhalia"]},
            {"name": "Junagadh", "cities": ["Junagadh", "Keshod"]},
            {"name": "Kutch", "cities": ["Bhuj", "Gandhidham", "Mandvi"]},
            {"name": "Kheda", "cities": ["Nadiad", "Kheda"]},
            {"name": "Mahisagar", "cities": ["Lunavada"]},
            {"name": "Mehsana", "cities": ["Mehsana", "Unjha"]},
            {"name": "Morbi", "cities": ["Morbi"]},
            {"name": "Narmada", "cities": ["Rajpipla"]},
            {"name": "Navsari", "cities": ["Navsari", "Valsad"]},
            {"name": "Panchmahal", "cities": ["Godhra", "Halol"]},
            {"name": "Patan", "cities": ["Patan", "Sidhpur"]},
            {"name": "Porbandar", "cities": ["Porbandar"]},
            {"name": "Rajkot", "cities": ["Rajkot", "Gondal", "Jetpur"]},
            {"name": "Sabarkantha", "cities": ["Himatnagar", "Idar"]},
            {"name": "Surat", "cities": ["Surat", "Navsari"]},
            {"name": "Surendranagar", "cities": ["Surendranagar", "Wadhwan"]},
            {"name": "Tapi", "cities": ["Vyara", "Songadh"]},
            {"name": "Vadodara", "cities": ["Vadodara", "Savli"]},
            {"name": "Valsad", "cities": ["Valsad", "Vapi"]}
        ]},
        {"name": "Haryana", "districts": [
            {"name": "Ambala", "cities": ["Ambala", "Ambala Cantt"]},
            {"name": "Bhiwani", "cities": ["Bhiwani", "Loharu"]},
            {"name": "Charkhi Dadri", "cities": ["Charkhi Dadri"]},
            {"name": "Faridabad", "cities": ["Faridabad", "Ballabgarh"]},
            {"name": "Fatehabad", "cities": ["Fatehabad", "Tohana"]},
            {"name": "Gurgaon", "cities": ["Gurgaon", "Manesar"]},
            {"name": "Hisar", "cities": ["Hisar", "Hansi"]},
            {"name": "Jhajjar", "cities": ["Jhajjar", "Bahadurgarh"]},
            {"name": "Jind", "cities": ["Jind", "Safidon"]},
            {"name": "Kaithal", "cities": ["Kaithal", "Pundri"]},
            {"name": "Karnal", "cities": ["Karnal", "Panipat"]},
            {"name": "Kurukshetra", "cities": ["Kurukshetra", "Thanesar"]},
            {"name": "Mahendragarh", "cities": ["Narnaul", "Mahendragarh"]},
            {"name": "Mewat", "cities": ["Nuh", "Ferozepur Jhirka"]},
            {"name": "Palwal", "cities": ["Palwal", "Hodal"]},
            {"name": "Panchkula", "cities": ["Panchkula", "Pinjore"]},
            {"name": "Panipat", "cities": ["Panipat", "Samalkha"]},
            {"name": "Rewari", "cities": ["Rewari", "Bawal"]},
            {"name": "Rohtak", "cities": ["Rohtak", "Meham"]},
            {"name": "Sirsa", "cities": ["Sirsa", "Rania"]},
            {"name": "Sonipat", "cities": ["Sonipat", "Ganaur"]},
            {"name": "Yamunanagar", "cities": ["Yamunanagar", "Jagadhri"]}
        ]},
        {"name": "Himachal Pradesh", "districts": [
            {"name": "Bilaspur", "cities": ["Bilaspur"]},
            {"name": "Chamba", "cities": ["Chamba"]},
            {"name": "Hamirpur", "cities": ["Hamirpur"]},
            {"name": "Kangra", "cities": ["Dharamshala", "Kangra", "Palampur"]},
            {"name": "Kinnaur", "cities": ["Reckong Peo"]},
            {"name": "Kullu", "cities": ["Kullu", "Manali"]},
            {"name": "Lahaul and Spiti", "cities": ["Keylong"]},
            {"name": "Mandi", "cities": ["Mandi", "Sundernagar"]},
            {"name": "Shimla", "cities": ["Shimla"]},
            {"name": "Sirmaur", "cities": ["Nahan", "Paonta Sahib"]},
            {"name": "Solan", "cities": ["Solan", "Baddi"]},
            {"name": "Una", "cities": ["Una"]},
            {"name": "Chamba", "cities": ["Chamba"]},
            {"name": "Kangra", "cities": ["Dharamshala"]}
        ]},
        {"name": "Jharkhand", "districts": [
            {"name": "Bokaro", "cities": ["Bokaro Steel City", "Chas"]},
            {"name": "Chatra", "cities": ["Chatra"]},
            {"name": "Deoghar", "cities": ["Deoghar"]},
            {"name": "Dhanbad", "cities": ["Dhanbad", "Jharia"]},
            {"name": "Dumka", "cities": ["Dumka"]},
            {"name": "East Singhbhum", "cities": ["Jamshedpur", "Steel City"]},
            {"name": "Garhwa", "cities": ["Garhwa"]},
            {"name": "Giridih", "cities": ["Giridih"]},
            {"name": "Godda", "cities": ["Godda"]},
            {"name": "Gumla", "cities": ["Gumla"]},
            {"name": "Hazaribagh", "cities": ["Hazaribagh"]},
            {"name": "Jamtara", "cities": ["Jamtara"]},
            {"name": "Khunti", "cities": ["Khunti"]},
            {"name": "Koderma", "cities": ["Koderma"]},
            {"name": "Latehar", "cities": ["Latehar"]},
            {"name": "Lohardaga", "cities": ["Lohardaga"]},
            {"name": "Pakur", "cities": ["Pakur"]},
            {"name": "Palamu", "cities": ["Daltonganj", "Palamu"]},
            {"name": "Paschim Singhbhum", "cities": ["Chaibasa"]},
            {"name": "Ranchi", "cities": ["Ranchi", "Khunti"]},
            {"name": "Sahibganj", "cities": ["Sahibganj"]},
            {"name": "Seraikela Kharsawan", "cities": ["Seraikela"]},
            {"name": "Simdega", "cities": ["Simdega"]},
            {"name": "West Singhbhum", "cities": ["Chaibasa"]}
        ]},
        {"name": "Karnataka", "districts": [
            {"name": "Bagalkot", "cities": ["Bagalkot", "Badami", "Kudalasangama"]},
            {"name": "Ballari", "cities": ["Ballari", "Hospet", "Koppal"]},
            {"name": "Belagavi", "cities": ["Belagavi", "Gokak", "Khanapur"]},
            {"name": "Bengaluru Rural", "cities": ["Devanahalli", "Doddaballapur"]},
            {"name": "Bengaluru Urban", "cities": ["Bengaluru", "Yelahanka"]},
            {"name": "Bidar", "cities": ["Bidar", "Bhalki"]},
            {"name": "Chamarajanagar", "cities": ["Chamarajanagar", "Kollegal"]},
            {"name": "Chikkaballapura", "cities": ["Chikkaballapura", "Gauribidanur"]},
            {"name": "Chikkamagaluru", "cities": ["Chikkamagaluru", "Mudigere"]},
            {"name": "Chitradurga", "cities": ["Chitradurga", "Hiriyur"]},
            {"name": "Dakshina Kannada", "cities": ["Mangaluru", "Puttur", "Bantwal"]},
            {"name": "Davanagere", "cities": ["Davanagere", "Harihar"]},
            {"name": "Dharwad", "cities": ["Dharwad", "Hubballi", "Navalgund"]},
            {"name": "Gadag", "cities": ["Gadag", "Laxmeshwar"]},
            {"name": "Hassan", "cities": ["Hassan", "Belur", "Sakleshpur"]},
            {"name": "Haveri", "cities": ["Haveri", "Ranebennur"]},
            {"name": "Kalaburagi", "cities": ["Kalaburagi", "Yadgir"]},
            {"name": "Kodagu", "cities": ["Madikeri", "Virajpet"]},
            {"name": "Kolar", "cities": ["Kolar", "Mulbagal"]},
            {"name": "Koppal", "cities": ["Koppal", "Gangavathi"]},
            {"name": "Mandya", "cities": ["Mandya", "Maddur", "Srirangapatna"]},
            {"name": "Mysuru", "cities": ["Mysuru", "Nanjangud"]},
            {"name": "Raichur", "cities": ["Raichur", "Manvi"]},
            {"name": "Ramanagara", "cities": ["Ramanagara", "Channapatna"]},
            {"name": "Shivamogga", "cities": ["Shivamogga", "Bhadravathi", "Sagar"]},
            {"name": "Tumakuru", "cities": ["Tumakuru", "Koratagere"]},
            {"name": "Udupi", "cities": ["Udupi", "Manipal", "Mangaluru"]},
            {"name": "Uttara Kannada", "cities": ["Karwar", "Sirsi", "Honnavar"]},
            {"name": "Vijayapura", "cities": ["Vijayapura", "Bagalkot"]},
            {"name": "Yadgir", "cities": ["Yadgir", "Shahapur"]},
            {"name": "Vijayanagara", "cities": ["Hospet"]}
        ]},
        {"name": "Kerala", "districts": [
            {"name": "Alappuzha", "cities": ["Alappuzha", "Cherthala"]},
            {"name": "Ernakulam", "cities": ["Kochi", "Thrissur", "Kalamassery"]},
            {"name": "Idukki", "cities": ["Kothamangalam", "Thodupuzha"]},
            {"name": "Kannur", "cities": ["Kannur", "Thalassery"]},
            {"name": "Kasaragod", "cities": ["Kasaragod", "Kanhangad"]},
            {"name": "Kollam", "cities": ["Kollam", "Paravur"]},
            {"name": "Kottayam", "cities": ["Kottayam", "Changanassery"]},
            {"name": "Kozhikode", "cities": ["Kozhikode", "Vadakara"]},
            {"name": "Malappuram", "cities": ["Malappuram", "Manjeri", "Tirur"]},
            {"name": "Palakkad", "cities": ["Palakkad", "Ottappalam"]},
            {"name": "Pathanamthitta", "cities": ["Pathanamthitta", "Adoor"]},
            {"name": "Thiruvananthapuram", "cities": ["Thiruvananthapuram", "Neyyattinkara"]},
            {"name": "Thrissur", "cities": ["Thrissur", "Guruvayur", "Irinjalakuda"]},
            {"name": "Wayanad", "cities": ["Kalpetta", "Sultan Bathery"]}
        ]},
        {"name": "Madhya Pradesh", "districts": [
            {"name": "Agar Malwa", "cities": ["Agar"]},
            {"name": "Alirajpur", "cities": ["Alirajpur"]},
            {"name": "Anuppur", "cities": ["Anuppur"]},
            {"name": "Ashoknagar", "cities": ["Ashoknagar"]},
            {"name": "Balaghat", "cities": ["Balaghat", "Waraseoni"]},
            {"name": "Barwani", "cities": ["Barwani", "Sendhwa"]},
            {"name": "Betul", "cities": ["Betul", "Amla"]},
            {"name": "Bhind", "cities": ["Bhind", "Mehgaon"]},
            {"name": "Bhopal", "cities": ["Bhopal"]},
            {"name": "Burhanpur", "cities": ["Burhanpur"]},
            {"name": "Chhatarpur", "cities": ["Chhatarpur", "Khajuraho"]},
            {"name": "Chhindwara", "cities": ["Chhindwara", "Pandhurna"]},
            {"name": "Damoh", "cities": ["Damoh"]},
            {"name": "Datia", "cities": ["Datia"]},
            {"name": "Dewas", "cities": ["Dewas", "Sonkatch"]},
            {"name": "Dhar", "cities": ["Dhar", "Mhow"]},
            {"name": "Dindori", "cities": ["Dindori"]},
            {"name": "Guna", "cities": ["Guna", "Raghogarh"]},
            {"name": "Gwalior", "cities": ["Gwalior", "Morena"]},
            {"name": "Harda", "cities": ["Harda", "Timarni"]},
            {"name": "Hoshangabad", "cities": ["Hoshangabad", "Itarsi"]},
            {"name": "Indore", "cities": ["Indore", "Mhow", "Pithampur"]},
            {"name": "Jabalpur", "cities": ["Jabalpur", "Sihora"]},
            {"name": "Jhabua", "cities": ["Jhabua", "Thandla"]},
            {"name": "Katni", "cities": ["Katni"]},
            {"name": "Khandwa", "cities": ["Khandwa", "Sanawad"]},
            {"name": "Khargone", "cities": ["Khargone", "Maheshwar"]},
            {"name": "Mandla", "cities": ["Mandla"]},
            {"name": "Mandsaur", "cities": ["Mandsaur", "Sitamau"]},
            {"name": "Morena", "cities": ["Morena", "Ambah"]},
            {"name": "Narsinghpur", "cities": ["Narsinghpur"]},
            {"name": "Neemuch", "cities": ["Neemuch", "Manasa"]},
            {"name": "Niwari", "cities": ["Niwari"]},
            {"name": "Panna", "cities": ["Panna"]},
            {"name": "Raisen", "cities": ["Raisen", "Begamganj"]},
            {"name": "Rajgarh", "cities": ["Rajgarh", "Sironj"]},
            {"name": "Ratlam", "cities": ["Ratlam", "Sailana"]},
            {"name": "Rewa", "cities": ["Rewa", "Satna"]},
            {"name": "Sagar", "cities": ["Sagar", "Khurai"]},
            {"name": "Sagar", "cities": ["Sagar"]},
            {"name": "Satna", "cities": ["Satna"]},
            {"name": "Sehore", "cities": ["Sehore", "Bhopal"]},
            {"name": "Seoni", "cities": ["Seoni", "Lakhnadon"]},
            {"name": "Shahdol", "cities": ["Shahdol"]},
            {"name": "Shajapur", "cities": ["Shajapur", "Sarangpur"]},
            {"name": "Sheopur", "cities": ["Sheopur"]},
            {"name": "Shivpuri", "cities": ["Shivpuri", "Kolaras"]},
            {"name": "Sidhi", "cities": ["Sidhi"]},
            {"name": "Singrauli", "cities": ["Singrauli"]},
            {"name": "Tikamgarh", "cities": ["Tikamgarh"]},
            {"name": "Ujjain", "cities": ["Ujjain", "Mahidpur"]},
            {"name": "Umaria", "cities": ["Umaria"]},
            {"name": "Vidisha", "cities": ["Vidisha", "Sironj"]}
        ]},
        {"name": "Maharashtra", "districts": [
            {"name": "Ahmednagar", "cities": ["Ahmednagar", "Shevgaon"]},
            {"name": "Akola", "cities": ["Akola", "Murtizapur"]},
            {"name": "Amravati", "cities": ["Amravati", "Badnera"]},
            {"name": "Aurangabad", "cities": ["Aurangabad", "Paithan"]},
            {"name": "Beed", "cities": ["Beed"]},
            {"name": "Bhandara", "cities": ["Bhandara", "Tumsar"]},
            {"name": "Buldhana", "cities": ["Buldhana", "Khamgaon"]},
            {"name": "Chandrapur", "cities": ["Chandrapur", "Ballarpur"]},
            {"name": "Dhule", "cities": ["Dhule", "Sindkheda"]},
            {"name": "Gadchiroli", "cities": ["Gadchiroli"]},
            {"name": "Gondia", "cities": ["Gondia", "Deori"]},
            {"name": "Hingoli", "cities": ["Hingoli"]},
            {"name": "Jalgaon", "cities": ["Jalgaon", "Bhusawal"]},
            {"name": "Kolhapur", "cities": ["Kolhapur", "Ichalkaranji"]},
            {"name": "Latur", "cities": ["Latur"]},
            {"name": "Mumbai City", "cities": ["Mumbai"]},
            {"name": "Mumbai Suburban", "cities": ["Mumbai", "Andheri"]},
            {"name": "Nagpur", "cities": ["Nagpur", "Kamptee"]},
            {"name": "Nanded", "cities": ["Nanded", "Kandhar"]},
            {"name": "Nandurbar", "cities": ["Nandurbar"]},
            {"name": "Nashik", "cities": ["Nashik", "Malegaon"]},
            {"name": "Osmanabad", "cities": ["Osmanabad", "Tuljapur"]},
            {"name": "Palghar", "cities": ["Palghar", "Vasai"]},
            {"name": "Parbhani", "cities": ["Parbhani"]},
            {"name": "Pune", "cities": ["Pune", "Pimpri-Chinchwad"]},
            {"name": "Raigad", "cities": ["Alibag", "Panvel"]},
            {"name": "Ratnagiri", "cities": ["Ratnagiri", "Chiplun"]},
            {"name": "Sangli", "cities": ["Sangli", "Miraj"]},
            {"name": "Satara", "cities": ["Satara", "Karad"]},
            {"name": "Sindhudurg", "cities": ["Sindhudurg", "Sawantwadi"]},
            {"name": "Solapur", "cities": ["Solapur", "Pandharpur"]},
            {"name": "Thane", "cities": ["Thane", "Kalyan-Dombivli"]},
            {"name": "Wardha", "cities": ["Wardha", "Sevagram"]},
            {"name": "Washim", "cities": ["Washim"]},
            {"name": "Yavatmal", "cities": ["Yavatmal"]},
            {"name": "Sindhudurg", "cities": ["Sindhudurg"]}
        ]},
        {"name": "Manipur", "districts": [
            {"name": "Bishnupur", "cities": ["Bishnupur"]},
            {"name": "Chandel", "cities": ["Chandel"]},
            {"name": "Churachandpur", "cities": ["Churachandpur"]},
            {"name": "Imphal East", "cities": ["Imphal", "Porompat"]},
            {"name": "Imphal West", "cities": ["Imphal", "Lamphelpat"]},
            {"name": "Jiribam", "cities": ["Jiribam"]},
            {"name": "Kakching", "cities": ["Kakching"]},
            {"name": "Kangpokpi", "cities": ["Kangpokpi"]},
            {"name": "Kamjong", "cities": ["Kamjong"]},
            {"name": "Noney", "cities": ["Noney"]},
            {"name": "Pherzawl", "cities": ["Pherzawl"]},
            {"name": "Senapati", "cities": ["Senapati"]},
            {"name": "Tamenglong", "cities": ["Tamenglong"]},
            {"name": "Tengnoupal", "cities": ["Tengnoupal"]},
            {"name": "Thoubal", "cities": ["Thoubal"]},
            {"name": "Ukhrul", "cities": ["Ukhrul"]}
        ]},
        {"name": "Meghalaya", "districts": [
            {"name": "East Garo Hills", "cities": ["Williamnagar"]},
            {"name": "East Jaintia Hills", "cities": ["Khliehriat"]},
            {"name": "East Khasi Hills", "cities": ["Shillong"]},
            {"name": "North Garo Hills", "cities": ["Resubelpara"]},
            {"name": "Ri Bhoi", "cities": ["Nongpoh"]},
            {"name": "South Garo Hills", "cities": ["Baghmara"]},
            {"name": "South West Garo Hills", "cities": ["Ampati"]},
            {"name": "South West Khasi Hills", "cities": ["Mawkyrwat"]},
            {"name": "West Garo Hills", "cities": ["Tura"]},
            {"name": "West Jaintia Hills", "cities": ["Jowai"]},
            {"name": "West Khasi Hills", "cities": ["Nongstoin"]}
        ]},
        {"name": "Mizoram", "districts": [
            {"name": "Aizawl", "cities": ["Aizawl"]},
            {"name": "Champhai", "cities": ["Champhai"]},
            {"name": "Kolasib", "cities": ["Kolasib"]},
            {"name": "Lawngtlai", "cities": ["Lawngtlai"]},
            {"name": "Lunglei", "cities": ["Lunglei"]},
            {"name": "Mamit", "cities": ["Mamit"]},
            {"name": "Saiha", "cities": ["Saiha"]},
            {"name": "Serchhip", "cities": ["Serchhip"]},
            {"name": "Hnahthial", "cities": ["Hnahthial"]},
            {"name": "Khawzawl", "cities": ["Khawzawl"]},
            {"name": "Saitual", "cities": ["Saitual"]}
        ]},
        {"name": "Nagaland", "districts": [
            {"name": "Dimapur", "cities": ["Dimapur", "Chumukedima"]},
            {"name": "Kiphire", "cities": ["Kiphire"]},
            {"name": "Kohima", "cities": ["Kohima"]},
            {"name": "Longleng", "cities": ["Longleng"]},
            {"name": "Mokokchung", "cities": ["Mokokchung"]},
            {"name": "Mon", "cities": ["Mon"]},
            {"name": "Peren", "cities": ["Peren"]},
            {"name": "Phek", "cities": ["Phek"]},
            {"name": "Tuensang", "cities": ["Tuensang"]},
            {"name": "Wokha", "cities": ["Wokha"]},
            {"name": "Zunheboto", "cities": ["Zunheboto"]},
            {"name": "Niuland", "cities": ["Niuland"]},
            {"name": "Tseminyu", "cities": ["Tseminyu"]},
            {"name": "Shamator", "cities": ["Shamator"]},
            {"name": "Noklak", "cities": ["Noklak"]},
            {"name": "Chumoukedima", "cities": ["Chumoukedima"]}
        ]},
        {"name": "Odisha", "districts": [
            {"name": "Angul", "cities": ["Angul", "Talcher"]},
            {"name": "Balangir", "cities": ["Balangir", "Titlagarh"]},
            {"name": "Balasore", "cities": ["Balasore", "Baripada"]},
            {"name": "Bargarh", "cities": ["Bargarh", "Borlam"]},
            {"name": "Bhadrak", "cities": ["Bhadrak", "Chandbali"]},
            {"name": "Cuttack", "cities": ["Cuttack", "Bhubaneswar"]},
            {"name": "Deogarh", "cities": ["Deogarh"]},
            {"name": "Dhenkanal", "cities": ["Dhenkanal", "Kamakshyanagar"]},
            {"name": "Gajapati", "cities": ["Paralakhemundi"]},
            {"name": "Ganjam", "cities": ["Berhampur", "Chhatrapur"]},
            {"name": "Jagatsinghpur", "cities": ["Jagatsinghpur", "Paradip"]},
            {"name": "Jajpur", "cities": ["Jajpur", "Bari"]},
            {"name": "Jharsuguda", "cities": ["Jharsuguda"]},
            {"name": "Kalahandi", "cities": ["Bhawanipatna", "Kesinga"]},
            {"name": "Kandhamal", "cities": ["Phulbani"]},
            {"name": "Kendrapara", "cities": ["Kendrapara", "Pattamundai"]},
            {"name": "Kendujhar", "cities": ["Barbil", "Kendujhar"]},
            {"name": "Khordha", "cities": ["Bhubaneswar", "Cuttack"]},
            {"name": "Koraput", "cities": ["Koraput", "Jeypore"]},
            {"name": "Malkangiri", "cities": ["Malkangiri"]},
            {"name": "Mayurbhanj", "cities": ["Baripada", "Rairangpur"]},
            {"name": "Nabarangpur", "cities": ["Nabarangpur"]},
            {"name": "Nayagarh", "cities": ["Nayagarh"]},
            {"name": "Nuapada", "cities": ["Nuapada", "Khariar"]},
            {"name": "Puri", "cities": ["Puri", "Konark"]},
            {"name": "Rayagada", "cities": ["Rayagada", "Gunupur"]},
            {"name": "Sambalpur", "cities": ["Sambalpur", "Rourkela"]},
            {"name": "Subarnapur", "cities": ["Subarnapur", "Birmaharajpur"]},
            {"name": "Sundargarh", "cities": ["Rourkela", "Sundargarh"]},
            {"name": "Gajapati", "cities": ["Paralakhemundi"]}
        ]},
        {"name": "Punjab", "districts": [
            {"name": "Amritsar", "cities": ["Amritsar"]},
            {"name": "Barnala", "cities": ["Barnala"]},
            {"name": "Bathinda", "cities": ["Bathinda"]},
            {"name": "Faridkot", "cities": ["Faridkot"]},
            {"name": "Fatehgarh Sahib", "cities": ["Fatehgarh Sahib"]},
            {"name": "Fazilka", "cities": ["Fazilka"]},
            {"name": "Firozpur", "cities": ["Firozpur"]},
            {"name": "Gurdaspur", "cities": ["Gurdaspur", "Pathankot"]},
            {"name": "Hoshiarpur", "cities": ["Hoshiarpur"]},
            {"name": "Jalandhar", "cities": ["Jalandhar"]},
            {"name": "Kapurthala", "cities": ["Kapurthala"]},
            {"name": "Ludhiana", "cities": ["Ludhiana"]},
            {"name": "Mansa", "cities": ["Mansa"]},
            {"name": "Moga", "cities": ["Moga"]},
            {"name": "Muktsar", "cities": ["Muktsar"]},
            {"name": "Nawanshahr", "cities": ["Nawanshahr"]},
            {"name": "Pathankot", "cities": ["Pathankot"]},
            {"name": "Patiala", "cities": ["Patiala"]},
            {"name": "Rupnagar", "cities": ["Rupnagar"]},
            {"name": "Sahibzada Ajit Singh Nagar", "cities": ["Mohali"]},
            {"name": "Sangrur", "cities": ["Sangrur"]},
            {"name": "Shahid Bhagat Singh Nagar", "cities": ["Nawanshahr"]},
            {"name": "Tarn Taran", "cities": ["Tarn Taran"]}
        ]},
        {"name": "Rajasthan", "districts": [
            {"name": "Ajmer", "cities": ["Ajmer", "Kishangarh"]},
            {"name": "Alwar", "cities": ["Alwar", "Bhiwadi"]},
            {"name": "Banswara", "cities": ["Banswara"]},
            {"name": "Baran", "cities": ["Baran"]},
            {"name": "Barmer", "cities": ["Barmer", "Balotra"]},
            {"name": "Bharatpur", "cities": ["Bharatpur"]},
            {"name": "Bhilwara", "cities": ["Bhilwara"]},
            {"name": "Bikaner", "cities": ["Bikaner"]},
            {"name": "Bundi", "cities": ["Bundi"]},
            {"name": "Chittorgarh", "cities": ["Chittorgarh"]},
            {"name": "Churu", "cities": ["Churu"]},
            {"name": "Dausa", "cities": ["Dausa"]},
            {"name": "Dholpur", "cities": ["Dholpur"]},
            {"name": "Dungarpur", "cities": ["Dungarpur"]},
            {"name": "Hanumangarh", "cities": ["Hanumangarh"]},
            {"name": "Jaipur", "cities": ["Jaipur", "Sikar"]},
            {"name": "Jaisalmer", "cities": ["Jaisalmer"]},
            {"name": "Jalore", "cities": ["Jalore"]},
            {"name": "Jhalawar", "cities": ["Jhalawar"]},
            {"name": "Jhunjhunu", "cities": ["Jhunjhunu"]},
            {"name": "Jodhpur", "cities": ["Jodhpur"]},
            {"name": "Karauli", "cities": ["Karauli"]},
            {"name": "Kota", "cities": ["Kota", "Bundi"]},
            {"name": "Nagaur", "cities": ["Nagaur"]},
            {"name": "Pali", "cities": ["Pali"]},
            {"name": "Pratapgarh", "cities": ["Pratapgarh"]},
            {"name": "Rajsamand", "cities": ["Rajsamand"]},
            {"name": "Sawai Madhopur", "cities": ["Sawai Madhopur"]},
            {"name": "Sikar", "cities": ["Sikar"]},
            {"name": "Sirohi", "cities": ["Sirohi", "Abu Road"]},
            {"name": "Sri Ganganagar", "cities": ["Sri Ganganagar"]},
            {"name": "Tonk", "cities": ["Tonk"]},
            {"name": "Udaipur", "cities": ["Udaipur", "Nathdwara"]}
        ]},
        {"name": "Sikkim", "districts": [
            {"name": "East Sikkim", "cities": ["Gangtok"]},
            {"name": "North Sikkim", "cities": ["Mangan"]},
            {"name": "South Sikkim", "cities": ["Namchi"]},
            {"name": "West Sikkim", "cities": ["Geyzing"]},
            {"name": "Pakyong", "cities": ["Pakyong"]},
            {"name": "Soreng", "cities": ["Soreng"]},
            {"name": "Namchi", "cities": ["Namchi"]},
            {"name": "Gyalshing", "cities": ["Gyalshing"]}
        ]},
        {"name": "Tamil Nadu", "districts": [
            {"name": "Ariyalur", "cities": ["Ariyalur"]},
            {"name": "Chengalpattu", "cities": ["Chengalpattu", "Tambaram"]},
            {"name": "Chennai", "cities": ["Chennai"]},
            {"name": "Coimbatore", "cities": ["Coimbatore", "Tiruppur"]},
            {"name": "Cuddalore", "cities": ["Cuddalore"]},
            {"name": "Dharmapuri", "cities": ["Dharmapuri"]},
            {"name": "Dindigul", "cities": ["Dindigul"]},
            {"name": "Erode", "cities": ["Erode"]},
            {"name": "Kallakurichi", "cities": ["Kallakurichi"]},
            {"name": "Kanchipuram", "cities": ["Kanchipuram"]},
            {"name": "Kanyakumari", "cities": ["Nagercoil", "Kanyakumari"]},
            {"name": "Karur", "cities": ["Karur"]},
            {"name": "Krishnagiri", "cities": ["Krishnagiri", "Hosur"]},
            {"name": "Madurai", "cities": ["Madurai"]},
            {"name": "Mayiladuthurai", "cities": ["Mayiladuthurai"]},
            {"name": "Nagapattinam", "cities": ["Nagapattinam"]},
            {"name": "Namakkal", "cities": ["Namakkal"]},
            {"name": "Nilgiris", "cities": ["Ooty", "Coonoor"]},
            {"name": "Perambalur", "cities": ["Perambalur"]},
            {"name": "Pudukkottai", "cities": ["Pudukkottai"]},
            {"name": "Ramanathapuram", "cities": ["Ramanathapuram"]},
            {"name": "Ranipet", "cities": ["Ranipet", "Arcot"]},
            {"name": "Salem", "cities": ["Salem"]},
            {"name": "Sivaganga", "cities": ["Sivaganga"]},
            {"name": "Tenkasi", "cities": ["Tenkasi"]},
            {"name": "Thanjavur", "cities": ["Thanjavur", "Kumbakonam"]},
            {"name": "Theni", "cities": ["Theni"]},
            {"name": "Thoothukudi", "cities": ["Thoothukudi", "Tuticorin"]},
            {"name": "Tiruchirappalli", "cities": ["Tiruchirappalli", "Trichy"]},
            {"name": "Tirunelveli", "cities": ["Tirunelveli"]},
            {"name": "Tirupathur", "cities": ["Tirupathur"]},
            {"name": "Tiruppur", "cities": ["Tiruppur"]},
            {"name": "Tiruvallur", "cities": ["Tiruvallur", "Avadi"]},
            {"name": "Tiruvannamalai", "cities": ["Tiruvannamalai"]},
            {"name": "Tiruvarur", "cities": ["Tiruvarur"]},
            {"name": "Vellore", "cities": ["Vellore"]},
            {"name": "Viluppuram", "cities": ["Viluppuram"]},
            {"name": "Virudhunagar", "cities": ["Virudhunagar", "Rajapalayam"]}
        ]},
        {"name": "Telangana", "districts": [
            {"name": "Adilabad", "cities": ["Adilabad", "Nirmal"]},
            {"name": "Bhadradri Kothagudem", "cities": ["Kothagudem", "Bhadrachalam"]},
            {"name": "Hyderabad", "cities": ["Hyderabad", "Secunderabad"]},
            {"name": "Jagtial", "cities": ["Jagtial", "Korutla"]},
            {"name": "Jangaon", "cities": ["Jangaon"]},
            {"name": "Jayashankar Bhupalpally", "cities": ["Bhupalpally"]},
            {"name": "Jogulamba Gadwal", "cities": ["Gadwal"]},
            {"name": "Kamareddy", "cities": ["Kamareddy"]},
            {"name": "Karimnagar", "cities": ["Karimnagar", "Jagitial"]},
            {"name": "Khammam", "cities": ["Khammam", "Kothagudem"]},
            {"name": "Kumuram Bheem Asifabad", "cities": ["Asifabad"]},
            {"name": "Mahabubabad", "cities": ["Mahabubabad"]},
            {"name": "Mahabubnagar", "cities": ["Mahabubnagar", "Narayanpet"]},
            {"name": "Mancherial", "cities": ["Mancherial"]},
            {"name": "Medak", "cities": ["Medak", "Sangareddy"]},
            {"name": "Medchal Malkajgiri", "cities": ["Medchal", "Malkajgiri"]},
            {"name": "Mulugu", "cities": ["Mulugu"]},
            {"name": "Nagarkurnool", "cities": ["Nagarkurnool"]},
            {"name": "Nalgonda", "cities": ["Nalgonda", "Miryalaguda"]},
            {"name": "Narayanpet", "cities": ["Narayanpet"]},
            {"name": "Nirmal", "cities": ["Nirmal"]},
            {"name": "Nizamabad", "cities": ["Nizamabad", "Kamareddy"]},
            {"name": "Peddapalli", "cities": ["Peddapalli"]},
            {"name": "Rajanna Sircilla", "cities": ["Sircilla"]},
            {"name": "Ranga Reddy", "cities": ["Shamshabad", "Chevella"]},
            {"name": "Sangareddy", "cities": ["Sangareddy"]},
            {"name": "Siddipet", "cities": ["Siddipet"]},
            {"name": "Suryapet", "cities": ["Suryapet"]},
            {"name": "Vikarabad", "cities": ["Vikarabad"]},
            {"name": "Wanaparthy", "cities": ["Wanaparthy"]},
            {"name": "Warangal Rural", "cities": ["Warangal"]},
            {"name": "Warangal Urban", "cities": ["Warangal", "Hanamkonda"]},
            {"name": "Yadadri Bhongir", "cities": ["Bhongir"]},
            {"name": "Medak", "cities": ["Medak"]}
        ]},
        {"name": "Tripura", "districts": [
            {"name": "Dhalai", "cities": ["Ambassa"]},
            {"name": "Gomati", "cities": ["Udaipur"]},
            {"name": "Khowai", "cities": ["Khowai"]},
            {"name": "North Tripura", "cities": ["Kailasahar"]},
            {"name": "Sepahijala", "cities": ["Bishalgarh"]},
            {"name": "South Tripura", "cities": ["Belonia"]},
            {"name": "Unakoti", "cities": ["Kailasahar"]},
            {"name": "West Tripura", "cities": ["Agartala"]}
        ]},
        {"name": "Uttar Pradesh", "districts": [
            {"name": "Agra", "cities": ["Agra", "Firozabad"]},
            {"name": "Aligarh", "cities": ["Aligarh"]},
            {"name": "Allahabad", "cities": ["Prayagraj", "Allahabad"]},
            {"name": "Ambedkar Nagar", "cities": ["Akbarpur"]},
            {"name": "Amethi", "cities": ["Gauriganj"]},
            {"name": "Amroha", "cities": ["Amroha"]},
            {"name": "Auraiya", "cities": ["Auraiya"]},
            {"name": "Azamgarh", "cities": ["Azamgarh"]},
            {"name": "Baghpat", "cities": ["Baghpat"]},
            {"name": "Bahraich", "cities": ["Bahraich"]},
            {"name": "Ballia", "cities": ["Ballia"]},
            {"name": "Balrampur", "cities": ["Balrampur"]},
            {"name": "Banda", "cities": ["Banda"]},
            {"name": "Barabanki", "cities": ["Barabanki"]},
            {"name": "Bareilly", "cities": ["Bareilly"]},
            {"name": "Basti", "cities": ["Basti"]},
            {"name": "Bhadohi", "cities": ["Bhadohi"]},
            {"name": "Bijnor", "cities": ["Bijnor"]},
            {"name": "Budaun", "cities": ["Budaun"]},
            {"name": "Bulandshahr", "cities": ["Bulandshahr"]},
            {"name": "Chandauli", "cities": ["Chandauli"]},
            {"name": "Chitrakoot", "cities": ["Chitrakoot"]},
            {"name": "Deoria", "cities": ["Deoria"]},
            {"name": "Etah", "cities": ["Etah"]},
            {"name": "Etawah", "cities": ["Etawah"]},
            {"name": "Farrukhabad", "cities": ["Farrukhabad"]},
            {"name": "Fatehpur", "cities": ["Fatehpur"]},
            {"name": "Firozabad", "cities": ["Firozabad"]},
            {"name": "Gautam Buddha Nagar", "cities": ["Noida", "Greater Noida"]},
            {"name": "Ghaziabad", "cities": ["Ghaziabad", "Modinagar"]},
            {"name": "Ghazipur", "cities": ["Ghazipur"]},
            {"name": "Gonda", "cities": ["Gonda"]},
            {"name": "Gorakhpur", "cities": ["Gorakhpur"]},
            {"name": "Hamirpur", "cities": ["Hamirpur"]},
            {"name": "Hapur", "cities": ["Hapur"]},
            {"name": "Hardoi", "cities": ["Hardoi"]},
            {"name": "Hathras", "cities": ["Hathras"]},
            {"name": "Jalaun", "cities": ["Orai"]},
            {"name": "Jaunpur", "cities": ["Jaunpur"]},
            {"name": "Jhansi", "cities": ["Jhansi"]},
            {"name": "Kannauj", "cities": ["Kannauj"]},
            {"name": "Kanpur Nagar", "cities": ["Kanpur"]},
            {"name": "Kanpur Dehat", "cities": ["Kanpur Dehat"]},
            {"name": "Kanshi Ram Nagar", "cities": ["Kasganj"]},
            {"name": "Kaushambi", "cities": ["Manjhanpur"]},
            {"name": "Kheri", "cities": ["Lakhimpur Kheri"]},
            {"name": "Kushi Nagar", "cities": ["Kushi Nagar"]},
            {"name": "Lalitpur", "cities": ["Lalitpur"]},
            {"name": "Lucknow", "cities": ["Lucknow"]},
            {"name": "Maharajganj", "cities": ["Maharajganj"]},
            {"name": "Mahoba", "cities": ["Mahoba"]},
            {"name": "Mainpuri", "cities": ["Mainpuri"]},
            {"name": "Mathura", "cities": ["Mathura", "Vrindavan"]},
            {"name": "Mau", "cities": ["Mau"]},
            {"name": "Meerut", "cities": ["Meerut"]},
            {"name": "Mirzapur", "cities": ["Mirzapur"]},
            {"name": "Moradabad", "cities": ["Moradabad"]},
            {"name": "Muzaffarnagar", "cities": ["Muzaffarnagar"]},
            {"name": "Pilibhit", "cities": ["Pilibhit"]},
            {"name": "Pratapgarh", "cities": ["Pratapgarh"]},
            {"name": "Prayagraj", "cities": ["Prayagraj", "Allahabad"]},
            {"name": "Rae Bareli", "cities": ["Rae Bareli"]},
            {"name": "Rampur", "cities": ["Rampur"]},
            {"name": "Saharanpur", "cities": ["Saharanpur"]},
            {"name": "Sambhal", "cities": ["Sambhal"]},
            {"name": "Sant Kabir Nagar", "cities": ["Khalilabad"]},
            {"name": "Sant Ravidas Nagar", "cities": ["Bhadohi"]},
            {"name": "Shahjahanpur", "cities": ["Shahjahanpur"]},
            {"name": "Shravasti", "cities": ["Shravasti"]},
            {"name": "Siddharthnagar", "cities": ["Siddharthnagar"]},
            {"name": "Sitapur", "cities": ["Sitapur"]},
            {"name": "Sonbhadra", "cities": ["Sonbhadra"]},
            {"name": "Sultanpur", "cities": ["Sultanpur"]},
            {"name": "Unnao", "cities": ["Unnao"]},
            {"name": "Varanasi", "cities": ["Varanasi"]},
            {"name": "Kanpur", "cities": ["Kanpur"]}
        ]},
        {"name": "Uttarakhand", "districts": [
            {"name": "Almora", "cities": ["Almora", "Ranikhet"]},
            {"name": "Bageshwar", "cities": ["Bageshwar"]},
            {"name": "Chamoli", "cities": ["Gopeshwar", "Joshimath"]},
            {"name": "Champawat", "cities": ["Champawat"]},
            {"name": "Dehradun", "cities": ["Dehradun", "Mussoorie"]},
            {"name": "Haridwar", "cities": ["Haridwar", "Rishikesh"]},
            {"name": "Nainital", "cities": ["Nainital", "Haldwani"]},
            {"name": "Pauri Garhwal", "cities": ["Pauri", "Kotdwara"]},
            {"name": "Pithoragarh", "cities": ["Pithoragarh"]},
            {"name": "Rudraprayag", "cities": ["Rudraprayag"]},
            {"name": "Tehri Garhwal", "cities": ["Tehri", "New Tehri"]},
            {"name": "Udham Singh Nagar", "cities": ["Kashipur", "Rudrapur"]},
            {"name": "Uttarkashi", "cities": ["Uttarkashi", "Gangotri"]},
            {"name": "Rudraprayag", "cities": ["Rudraprayag"]}
        ]},
        {"name": "West Bengal", "districts": [
            {"name": "Alipurduar", "cities": ["Alipurduar"]},
            {"name": "Bankura", "cities": ["Bankura", "Bishnupur"]},
            {"name": "Birbhum", "cities": ["Suri", "Bolpur"]},
            {"name": "Cooch Behar", "cities": ["Cooch Behar"]},
            {"name": "Dakshin Dinajpur", "cities": ["Balurghat"]},
            {"name": "Darjeeling", "cities": ["Darjeeling", "Siliguri", "Kurseong"]},
            {"name": "Hooghly", "cities": ["Chinsurah", "Serampore", "Chandannagar"]},
            {"name": "Howrah", "cities": ["Howrah", "Bally"]},
            {"name": "Jalpaiguri", "cities": ["Jalpaiguri", "Siliguri"]},
            {"name": "Jhargram", "cities": ["Jhargram"]},
            {"name": "Kalimpong", "cities": ["Kalimpong"]},
            {"name": "Kolkata", "cities": ["Kolkata"]},
            {"name": "Malda", "cities": ["Malda", "English Bazar"]},
            {"name": "Murshidabad", "cities": ["Berhampore", "Baharampur"]},
            {"name": "Nadia", "cities": ["Krishnanagar", "Kalyani"]},
            {"name": "North 24 Parganas", "cities": ["Barasat", "Barrackpore"]},
            {"name": "Paschim Bardhaman", "cities": ["Asansol", "Durgapur"]},
            {"name": "Paschim Medinipur", "cities": ["Medinipur", "Kharagpur"]},
            {"name": "Purba Bardhaman", "cities": ["Bardhaman", "Durgapur"]},
            {"name": "Purba Medinipur", "cities": ["Tamluk", "Haldia"]},
            {"name": "Purulia", "cities": ["Purulia", "Raghunathpur"]},
            {"name": "South 24 Parganas", "cities": ["Kolkata", "Baruipur"]},
            {"name": "Uttar Dinajpur", "cities": ["Raiganj", "Dinajpur"]},
            {"name": "Jalpaiguri", "cities": ["Jalpaiguri"]}
        ]},
        {"name": "Andaman and Nicobar", "districts": [
            {"name": "South Andaman", "cities": ["Port Blair"]},
            {"name": "North and Middle Andaman", "cities": ["Mayabunder"]},
            {"name": "Nicobar", "cities": ["Car Nicobar"]}
        ]},
        {"name": "Chandigarh", "districts": [
            {"name": "Chandigarh", "cities": ["Chandigarh"]}
        ]},
        {"name": "Dadra and Nagar Haveli and Daman and Diu", "districts": [
            {"name": "Dadra and Nagar Haveli", "cities": ["Silvassa"]},
            {"name": "Daman", "cities": ["Daman"]},
            {"name": "Diu", "cities": ["Diu"]}
        ]},
        {"name": "Delhi", "districts": [
            {"name": "Central Delhi", "cities": ["New Delhi"]},
            {"name": "East Delhi", "cities": ["Preet Vihar"]},
            {"name": "New Delhi", "cities": ["Connaught Place"]},
            {"name": "North Delhi", "cities": ["Civil Lines"]},
            {"name": "North East Delhi", "cities": ["Seelampur"]},
            {"name": "North West Delhi", "cities": ["Rohini"]},
            {"name": "Shahdara", "cities": ["Shahdara"]},
            {"name": "South Delhi", "cities": ["Saket"]},
            {"name": "South East Delhi", "cities": ["Okhla"]},
            {"name": "South West Delhi", "cities": ["Dwarka"]},
            {"name": "West Delhi", "cities": ["Rajouri Garden"]}
        ]},
        {"name": "Jammu and Kashmir", "districts": [
            {"name": "Anantnag", "cities": ["Anantnag"]},
            {"name": "Bandipora", "cities": ["Bandipora"]},
            {"name": "Baramulla", "cities": ["Baramulla", "Sopore"]},
            {"name": "Budgam", "cities": ["Budgam"]},
            {"name": "Doda", "cities": ["Doda"]},
            {"name": "Ganderbal", "cities": ["Ganderbal"]},
            {"name": "Jammu", "cities": ["Jammu"]},
            {"name": "Kathua", "cities": ["Kathua"]},
            {"name": "Kishtwar", "cities": ["Kishtwar"]},
            {"name": "Kulgam", "cities": ["Kulgam"]},
            {"name": "Kupwara", "cities": ["Kupwara"]},
            {"name": "Poonch", "cities": ["Poonch"]},
            {"name": "Pulwama", "cities": ["Pulwama"]},
            {"name": "Rajouri", "cities": ["Rajouri"]},
            {"name": "Ramban", "cities": ["Ramban"]},
            {"name": "Reasi", "cities": ["Reasi"]},
            {"name": "Samba", "cities": ["Samba"]},
            {"name": "Shopian", "cities": ["Shopian"]},
            {"name": "Srinagar", "cities": ["Srinagar"]},
            {"name": "Udhampur", "cities": ["Udhampur"]}
        ]},
        {"name": "Ladakh", "districts": [
            {"name": "Leh", "cities": ["Leh"]},
            {"name": "Kargil", "cities": ["Kargil"]}
        ]},
        {"name": "Lakshadweep", "districts": [
            {"name": "Lakshadweep", "cities": ["Kavaratti"]}
        ]},
        {"name": "Puducherry", "districts": [
            {"name": "Pondicherry", "cities": ["Pondicherry"]},
            {"name": "Karaikal", "cities": ["Karaikal"]},
            {"name": "Mahe", "cities": ["Mahe"]},
            {"name": "Yanam", "cities": ["Yanam"]}
        ]}
    ]
    
    added_states = 0
    added_districts = 0
    added_cities = 0
    
    for state_data in states_to_add:
        # Check if state already exists
        existing_state = db.query(State).filter(State.name == state_data["name"]).first()
        
        if not existing_state:
            # Add new state
            new_state = State(name=state_data["name"])
            db.add(new_state)
            db.commit()
            db.refresh(new_state)
            
            print(f"✅ Added State: {state_data['name']} (ID: {new_state.id})")
            added_states += 1
            
            # Add districts and cities for this state
            for district_data in state_data["districts"]:
                existing_district = db.query(District).filter(
                    District.name == district_data["name"],
                    District.state_id == new_state.id
                ).first()
                
                if not existing_district:
                    new_district = District(
                        name=district_data["name"],
                        state_id=new_state.id
                    )
                    db.add(new_district)
                    db.commit()
                    db.refresh(new_district)
                    
                    print(f"   └─ Added District: {district_data['name']} (ID: {new_district.id})")
                    added_districts += 1
                    
                    # Add cities for this district
                    if "cities" in district_data:
                        for city_name in district_data["cities"]:
                            existing_city = db.query(City).filter(
                                City.name == city_name,
                                City.district_id == new_district.id
                            ).first()
                            
                            if not existing_city:
                                new_city = City(
                                    name=city_name,
                                    district_id=new_district.id
                                )
                                db.add(new_city)
                                db.commit()
                                
                                print(f"      └─ Added City: {city_name}")
                                added_cities += 1
        else:
            print(f"⚠️  State already exists: {state_data['name']}")
    
    print("\n" + "=" * 50)
    print(f"📊 Summary:")
    print(f"   └─ States Added: {added_states}")
    print(f"   └─ Districts Added: {added_districts}")
    print(f"   └─ Cities Added: {added_cities}")
    print("✅ States, districts, and cities addition complete!")
    
    db.close()

if __name__ == "__main__":
    add_states_and_districts()
